# Taskfile for the X-Universe Data Extraction Pipeline
version: '3'

vars:
  PYTHON: 'python'

  # --- File & Directory Definitions ---
  ZIP_FILE: x4-foundations-wiki.zip
  SUMMARIZER_PROMPT: prompts/document_summarizer_prompt.txt
  
  SANITIZED_DIR: x4-foundations-wiki/hashed_pages
  MD_PAGES_DIR: x4-foundations-wiki/pages_md
  SUMMARIZED_PAGES_DIR: x4-foundations-wiki/pages_summarized
  VECTOR_STORE_DIR: faiss_index
  KEYWORDS_CACHE_DIR: .keyword_cache
  
  ALL_CHUNKS_FILE: x4_wiki_chunks.json
  KEYWORDS_FILE: x4_keywords.json
  REFINED_KEYWORDS_FILE: x4_keywords_refined.json

  MARKER_FILE: .task_complete

tasks:
  default:
    desc: Lists all available tasks.
    cmds:
      - task --list-all
    silent: true

  # ---------------------------------------------------------------------------
  # --- Main Targets
  # ---------------------------------------------------------------------------

  run:
    desc: (Default) Builds all data and starts the FastAPI server.
    deps: [all]
    cmds:
      - '{{.PYTHON}} src/main.py'

  all:
    desc: Builds all data artifacts required by the application.
    deps: [6-keywords-refined]

  # ---------------------------------------------------------------------------
  # --- Data Processing Pipeline (in order)
  # ---------------------------------------------------------------------------

  '1-data':
    desc: 'Step 1: Unzips and sanitizes the raw wiki HTML data.'
    sources:
      - '{{.ZIP_FILE}}'
      - src/00_unzip_data.py
    generates:
      - '{{.SANITIZED_DIR}}/{{.MARKER_FILE}}'
    cmds:
      - '{{.PYTHON}} src/00_unzip_data.py'
      - touch {{.SANITIZED_DIR}}/{{.MARKER_FILE}}

  '2-markdown':
    desc: 'Step 2: Converts HTML files to Markdown in parallel.'
    deps: ['1-data']
    sources:
      - '{{.SANITIZED_DIR}}/{{.MARKER_FILE}}'
      - src/01a_html_to_md.py
      - src/01c_get_files_to_process.py
    generates:
      - '{{.MD_PAGES_DIR}}/{{.MARKER_FILE}}'
    cmds:
      - '{{.PYTHON}} src/01c_get_files_to_process.py {{.SANITIZED_DIR}} {{.MD_PAGES_DIR}} .html .md | xargs -P 8 -I {} {{.PYTHON}} src/01a_html_to_md.py {}'
      - touch {{.MD_PAGES_DIR}}/{{.MARKER_FILE}}

  '3-markdown-summaries':
    desc: 'Step 3: Enriches markdown files with summaries and unrolled data.'
    deps: ['2-markdown']
    sources:
      - '{{.MD_PAGES_DIR}}/{{.MARKER_FILE}}'
      - src/01b_summarize_md.py
      - src/01c_get_files_to_process.py
      - '{{.SUMMARIZER_PROMPT}}'
    generates:
      - '{{.SUMMARIZED_PAGES_DIR}}/{{.MARKER_FILE}}'
    cmds:
      - '{{.PYTHON}} src/01c_get_files_to_process.py {{.MD_PAGES_DIR}} {{.SUMMARIZED_PAGES_DIR}} .md .md | xargs -P 2 -I {} {{.PYTHON}} src/01b_summarize_md.py {}'
      - touch {{.SUMMARIZED_PAGES_DIR}}/{{.MARKER_FILE}}
  
  '4-chunks':
    desc: 'Step 4: Breaks down all summarized/enriched markdown files into smaller chunks.'
    deps: ['3-markdown-summaries']
    sources:
      - '{{.SUMMARIZED_PAGES_DIR}}/{{.MARKER_FILE}}'
      - src/02_chunk_corpus.py
    generates:
      - '{{.ALL_CHUNKS_FILE}}'
    cmds:
      - '{{.PYTHON}} src/02_chunk_corpus.py'

  '5-vector-store':
    desc: 'Step 5: Creates a FAISS vector store from the merged chunks.'
    deps: ['4-chunks']
    sources:
      - '{{.ALL_CHUNKS_FILE}}'
      - src/03_build_vector_store.py
    generates:
      - '{{.VECTOR_STORE_DIR}}/{{.MARKER_FILE}}'
    cmds:
      - '{{.PYTHON}} src/03_build_vector_store.py'
      - touch {{.VECTOR_STORE_DIR}}/{{.MARKER_FILE}}

  '6-keywords':
    desc: 'Step 6: Generates keywords from the data chunks.'
    deps: ['5-vector-store']
    sources:
      - '{{.VECTOR_STORE_DIR}}/{{.MARKER_FILE}}'
      - src/04_generate_keywords.py
    generates:
      - '{{.KEYWORDS_FILE}}'
    cmds:
      - '{{.PYTHON}} src/04_generate_keywords.py'

  '6-keywords-refined':
    desc: 'Step 7: Filters the keyword list to create a domain-specific list.'
    deps: ['6-keywords']
    sources:
      - '{{.KEYWORDS_FILE}}'
      - src/05_refine_keywords.py
    generates:
      - '{{.REFINED_KEYWORDS_FILE}}'
    cmds:
      - '{{.PYTHON}} src/05_refine_keywords.py'

  # ---------------------------------------------------------------------------
  # --- Clean Tasks
  # ---------------------------------------------------------------------------

  clean:
    desc: Removes all generated data, caches, and artifacts.
    deps:
      - clean:data
      - clean:markdown
      - clean:markdown-summaries
      - clean:chunks
      - clean:vector-store
      - clean:keywords

  clean:data:
    desc: Deletes the unzipped and sanitized HTML data.
    cmds:
      - rm -rf {{.SANITIZED_DIR}}

  clean:markdown:
    desc: Deletes the generated markdown pages.
    cmds:
      - rm -rf {{.MD_PAGES_DIR}}

  clean:markdown-summaries:
    desc: Deletes the summarized markdown pages.
    cmds:
      - rm -rf {{.SUMMARIZED_PAGES_DIR}}

  clean:chunks:
    desc: Deletes all generated chunk files.
    cmds:
      - rm -f {{.ALL_CHUNKS_FILE}}

  clean:vector-store:
    desc: Deletes the FAISS vector store.
    cmds:
      - rm -rf {{.VECTOR_STORE_DIR}}

  clean:keywords:
    desc: Deletes all keyword files and the cache.
    cmds:
      - rm -rf {{.KEYWORDS_CACHE_DIR}}
      - rm -f {{.KEYWORDS_FILE}} {{.REFINED_KEYWORDS_FILE}}

